before:
  hooks:
    - go mod tidy
builds:
  - id: "kafkaques"
    binary: kafkaques
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
      - -v
    ldflags:
      - main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
release:
  prerelease: auto
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - id: kafkaques
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.release
    image_templates:
    - ghcr.io/kakkoyun/kafkaques:{{ .Tag }}
